# Site settings
title: Programming Illusions
email: alex.landini@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://landal79.github.io"
twitter_username: landal79
github_username:  landal79

# Build settings
markdown: kramdown

timezone: Europe/Rome
highlighter: pygments

#pagination
paginate: 5
paginate_path: "/blog/page:num/"
