# Site settings
title: Programming illusions
subtitle: Programming is an illusion, but I'm not an illusionist
email: alex.landini@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://landal79.github.io"
twitter_username: landal79
github_username:  landal79
linkedin_username: alexlandini

# Build settings
markdown: kramdown

timezone: Europe/Rome
highlighter: pygments

#pagination
paginate: 10
paginate_path: "/blog/page:num/"
permalink: pretty

#tags
tag_dir: /tag/
tag_layout: "article_by_tag.html"

#gems:
#  - jekyll-archives

jekyll-archives:
  enabled: []
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
